myfighter_felix_dlc.tesla()
myfighter_felix_dlc.ghost()
myfighter_felix_dlc.bat()
myfighter_felix_dlc.dragon()
myfighter_felix_dlc.dreadfulTeacher()
myfighter_chuxuan_dlc.chuxuan()
myfighter_yuen_dlc.yuen()
playGame.characterMenus()
